### ISSUE TITLE
[Plugin] [NetLogoTask] Run 3D models

### ISSUE THREAD

**Issue by helenea** [openmole/openmole#412] opened 2019-05-06 14:08 UTC
Would it be possible to modify the NetLogoTask to be able to run NetLogo 3D models (files with .nlogo3d extension) in OpenMOLE ?
I have no idea how difficult this might be but it would be so great if it was possible!

**Comment by JusteRaimbault** [comment] 2019-05-06 14:30
I never retried the netlogo 3d app since basically playing with it while discovering netlogo in ancient times ; is there a specific feature beyond the 3d visualization that would justify such a modification in the plugin ? (like z coordinates for agents I guess ? )

**Comment by JusteRaimbault** [comment] 2019-05-06 14:33
ah yes it is indeed the z coordinates and associated primitives. I'm checking if there is an headless version and api for nl3d

**Comment by JusteRaimbault** [comment] 2019-05-06 14:43
Given that the netlogo 6 api includes World3D (see [here](http://ccl.northwestern.edu/netlogo/docs/scaladoc/org/nlogo/api/World3D.html) ) and given the low level integration and interaction level we have with the netlogo workspace, I guess it could be quite straigtforward. @helenea do you **urgently** need this or can it wait until the coding camp as a low brain evening task for example ?

**Comment by helenea** [comment] 2019-05-06 14:46
It can wait until the coding camp! Thanks =D

**Comment by JusteRaimbault** [comment] 2019-05-06 14:56
well maybe I answered too fast, a bit more investigations show that it is handled in the api (so you can write 3d extensions) but does not seems to be in headless workspaces, so it may be impossible to do indeed (but not so sure as the netlogo doc is rather minimalist)

**Comment by JusteRaimbault** [comment] 2019-05-06 14:58
but digging into NL's code shows finally that it is :) (same as OpenMOLE, when the doc is fuzzy or incomplete or deprecated, the code speaks for itself ^^ )

**Comment by helenea** [comment] 2019-05-06 15:02
Unfortunately the code doesn't speak to everyone... ^^
But this is great news!

**Comment by JusteRaimbault** [comment] 2019-05-06 15:34
well it speaks when commented ;)
hum strange I'm testing, theoretically it should work without doing anything but it doesnt ; trying on a bare headless nl out of oml to see if it is a problem with us loading or not loading some classes

**Comment by JusteRaimbault** [comment] 2019-05-07 08:58
follow up thanks to @helenea : the `-Dorg.nlogo.is3d=true` jvm option may be necessary, what make things more complicated as we cannot change jvm args once oml is running and it makes no sense to pass the argument at openmole launchtime. I dig more into netlogo code

**Comment by JusteRaimbault** [comment] 2019-05-07 15:01
I just checked it is indeed how netlogo works, the `org.netlogo.api.Version` class checks the system property to tell if in 3d mode or not. I try to set the property before loading the script in `Netlogo.java`

**Comment by JusteRaimbault** [comment] 2019-05-07 16:22
Made a fix which makes 3d model working, but it is then impossible to run 2d and 3d models simultaneously. A modification of netlogo code may be necessary.

**Comment by JusteRaimbault** [comment] 2019-05-08 11:28
See this [Netlogo issue](https://github.com/NetLogo/NetLogo/issues/1742) , this may be more complicated than we thought

**Comment by JusteRaimbault** [comment] 2019-05-08 17:09
I managed to hack Netlogo to get simultaneously running 2d and 3d headless workspaces (minimalist test [here](https://github.com/JusteRaimbault/SimulationModels/blob/master/Models/tests/NetLogo3D/test_headless/java/Main.java) ) ; need however to check if it does not break the NetLogo GUI app and other stuff before doing a PR ; then if it is in a next release we will integrate it in OpenMOLE

**Comment by romainreuillon** [comment] 2019-05-08 19:38
:tophat:

**Comment by helenea** [comment] 2019-05-13 08:29
I'm not sure I understand, running one 3D model should work in OpenMOLE now, is that it?

**Comment by JusteRaimbault** [comment] 2019-05-13 08:52
no as we embed the netlogo artefact from ccl website so we need to wait for the modifications to be integrated in a netlogo release (what can be quite long - check the nl issue referenced above doing the 3d-2d integration in the gui app is an enormous amount of work already began in a branch so they may not accept my pull request which does just a quickndirty fix for headless tasks (what is enough for us).

if you really need we can do an openmole's branch which embeds the netlogo branch I modified and then you would be able to do that.

or we can do an ultra dirty quickfix in openmole only, which will enable to run 3d models and 2d models separately, but both in parallel will fail. then we need to be clear in the doc that it will fail.

**Comment by helenea** [comment] 2019-05-13 09:08
Oh ok.
Well if it's not too much work, I would vote for the openmole branch embedding the netlogo branch, as I'd like to be able to do my model exploration with openmole and I have no choice about using a 3d model. Maybe we can take a moment during the coding camp to discuss this?

**Comment by JusteRaimbault** [comment] 2019-05-13 09:13
yes we can 💪

**Comment by JusteRaimbault** [comment] 2019-05-13 09:15
or I can push now the quickndirty fix and put it as an undocumented option so only you would know it and the associated issues

**Comment by helenea** [comment] 2019-05-13 09:18
Yep that works too if you have time, and if it's too dirty and issue-prone we'll discuss it next week :smiley:

**Comment by JusteRaimbault** [comment] 2019-05-13 09:19
no it's not at all, the only side effect is that you cannot run simultaneously 2d and 3d models

**Comment by JusteRaimbault** [comment] 2019-05-13 09:19
but sequentially you can - it's this global jvm variable problem

**Comment by helenea** [comment] 2019-05-13 09:28
I only have one 3d model so that's not a problem for me at this time!

**Comment by JusteRaimbault** [comment] 2019-05-13 09:57
[35763fe](https://github.com/openmole/openmole/commit/35763feed0f3296d6678ba4395c677246ac3b2b9) implements this.
to run 3d models, use the arguments `switch3d` in `NetLogoTask5` and `NetLogoTask6` constructor, as this : 
`NetLogo6Task(workDirectory / "Flocking3D.nlogo3d", cmds, switch3d = true)`
When the `switch3d` option is set to `true`, the task will check the postfix of file name and activate/deactivate 3d depending if it ends with "3d". The option activates the switching, but does not directly do the switching, to prevent unexpected behaviors - if you do `switch3d = true` with a 2d model it will also work.
Dangerous behavior : if you run a 3d model and then a 2d but forgetting the switch argument it will logically fail

**Comment by JusteRaimbault** [comment] 2019-05-13 09:58
ok regarding the last point maybe it's better to set to 2d by default, and activate 3d only if switch is true AND model is actually 3d (regarding this we just check file name, file parsing and version checking before loading worksapce owuld be possible but a pain for not that much)

**Comment by JusteRaimbault** [comment] 2019-05-13 10:02
just pushed a correction to the previous point.
you can update your openmole and test it (I tested it on local with a toy model).
I close the issue, maybe we'll reopen it later depending on the evolution on netlogo side ; furthermore let's not document this for now as it is only a temporary fix.

**Closed by JusteRaimbault** 2019-05-13 10:02 UTC
Labels: enhancement, plugin

**Comment by helenea** [comment] 2019-05-27 10:08
Now that we can import and run 3D models in openmole, it would be useful to be able to open and edit the .nlogo3d files directly in the editor. @mathieuleclaire is it possible (in the same way we can open and edit .nlogo files)?

**Comment by mathieuleclaire** [comment] 2019-05-27 10:09
yes it is.

**Comment by mathieuleclaire** [comment] 2019-05-27 16:32
Implemented in 4bc21c3e0219df6e25219aac5d833190377d47bf
