### ISSUE TITLE
Very large workflow crashes h2 database?

### ISSUE THREAD

**Issue by julienperret** [openmole/openmole#404] opened 2019-04-15 13:49 UTC
When I try to run a large workflow (especially using large datasets), I get the following error:

> org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "REPLICAS" not found; SQL statement:
select "ID", "SOURCE", "STORAGE", "PATH", "HASH", "LAST_CHECK_EXISTS" from "REPLICAS" where ("HASH" in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)) and ("STORAGE" in (?, ?)) [42102-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7146)
	at org.h2.command.Parser.readTableFilter(Parser.java:1895)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2641)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2788)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2636)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2469)
	at org.h2.command.Parser.parseSelect(Parser.java:2440)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:349)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:322)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:312)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:434)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:47)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:217)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:217)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Any Idea

**Comment by JusteRaimbault** [comment] 2019-04-15 13:59
Not sure it is specifically related to large datasets, I had the same issue the other day on the myopenmole instance with a relatively small script ; really no idea where it could come from (no idea why it stopped also, except my openmole version was updated)

**Comment by julienperret** [comment] 2019-04-15 14:06
OK. I'll try updating and restarting it.

**Comment by julienperret** [comment] 2019-04-15 14:21
A restart seems to solve it. Thanks!

**Comment by julienperret** [comment] 2019-04-16 07:03
It came back after a few hours.
Any pointers?

**Comment by JusteRaimbault** [comment] 2019-04-16 07:43
is it only when trying to run on the grid or on any environment ?

**Comment by JusteRaimbault** [comment] 2019-04-16 07:54
tried to launch an experiment to check but seems like the grid is down :/ (no webdav working)

**Comment by JusteRaimbault** [comment] 2019-05-27 13:10
As the issue seems to be not reproducible, I'm closing it - please reopen with new information if it happens again

**Closed by JusteRaimbault** 2019-05-27 13:10 UTC
Labels: bug
