### ISSUE TITLE
Scrolling down bug

### ISSUE THREAD

**Issue by reyman** [openmole/openmole#210] opened 2017-05-15 17:27 UTC
Hi OpenMOLE team,

Another Gui problem during worklow writing. I don't know why, but in some case it's impossible to scroll down to see the complete workflow, as you can see in the attached picture. Scroll is blocked before the end.

![selection_016](https://cloud.githubusercontent.com/assets/466329/26070306/74472d46-39a4-11e7-9392-b96ba083f7ee.jpg)

**Comment by jopasserat** [comment] 2017-06-14 19:23
Closed as duplicate of #206

**Closed by jopasserat** 2017-06-14 19:23 UTC
Labels: bug, GUI
