### ISSUE TITLE
Too long folder name is not visible

### ISSUE THREAD

**Issue by jopasserat** [openmole/openmole#355] opened 2018-07-18 18:35 UTC
When a folder name, or sequence of names, gets too long in the workspace panel, it gets displayed outside the white background box and thus becomes hardly distinguishable from the black background.

Here an example:

![screenshot from 2018-06-19 15-58-45](https://user-images.githubusercontent.com/472083/42900654-57d64b3c-8ac1-11e8-987f-7260e9e6d45d.png)

Don't know what's the best approach:
  - Extend the white background box?
  - Truncate the folder name/sequence to keep it all on one line?

**Comment by mathieuleclaire** [comment] 2018-07-18 21:06
It is not a bug; to see the full name, click on the settings icon on the right.

![extendedname](https://user-images.githubusercontent.com/800035/42907797-3110f556-8adf-11e8-8189-fbaad32ecfeb.png)

**Comment by chapinux** [comment] 2018-07-19 08:48
<Sorry for the long comment>

this is loosely related to my tiny issue as the GUI tries its best to handle long/wide stuff : list of files and long folder names. (btw mine was about long lists and easily resolved with the filter tool).

But,
The problem @jopasserat  mentions is more panifull as it is related to everyday file browsing, if you have longnames folders inside longnames folders.

I guess the path display zone (black text  on white field )  content is formatted to stay in the file/folder left panel .

When long names are displayed, carriage returns makes their names being displayed in very darkgrey _under_ the white field, on a black background, making them hardly readable.

Also, long folder names are directly written under the last pipe sign, (a nasty carriage return I guess) so if you have a long name folde YYYY  within another long name folderXXXX,
 the parent folder (XXXX) is not written in the white zone of the path field but under it (darkgrey on black)
So if you are in YYYY (also written in darkgrey on black, just after XXXX), you cannot go back to XXXX, since it is barely clickable

This is not about getting the full name of a file (which is already possible & useful, thx to @mathieuleclaire answer), but being able to read the current working directory
This may not be a bug , but still,  a non browsable path is annoying, the sole solution is to click on the home icon and dive again int the depth of our results folder structure.

Naïve Suggestions : 
* double the path filed zone (seems easy)
* cut the head of the path and display only the last 3-4 subfolders (medium)(does not solves the problem of carriage returns int the black zone)
* add "parent directory" button  (seems easy)
* use the right panel for an arborescent  file view with expand/collapse tree folder structure  (hardcore & overkill)

Eventually, this gives me a cool name idea for a future shoegaze album : "Carriage Return in the Black Zone"

**Comment by mathieuleclaire** [comment] 2018-07-19 08:59
Well, it is hard to figure out what your are talking about. Peharp's a small video would be more relevant ?

**Comment by chapinux** [comment] 2018-07-19 09:10
I tried my best ....
Video in preparation

**Comment by mathieuleclaire** [comment] 2018-07-19 09:32
OK, I get it. The problem occur in the top navigation bar for long folders. I'll look into it.

**Comment by chapinux** [comment] 2018-07-19 09:33
So my english is too poor to describe it properly ?
Ok I made a Video , bam , like that.

Video is at https://nextcloud.iscpif.fr/index.php/s/Zitk4YsbsL6TNZm,
password is the name of the future SCIC 

It is also shared with you @mathieuleclaire via the lab's cloud 

Enjoy (I hope I won't have to make a video at each issue XD )

**Closed** 2018-07-19 16:36 UTC
Labels: GUI, bug
